declare const BRAND: unique symbol;
export type Brand<T, B extends string> = T & { readonly [BRAND]: B };
export type EntityId = Brand<string, 'EntityId'>;
export type ClaimId = Brand<string, 'ClaimId'>;
export type SourceId = Brand<string, 'SourceId'>;
export const entityId = (s: string): EntityId => s as EntityId;
export const claimId = (s: string): ClaimId => s as ClaimId;
export const sourceId = (s: string): SourceId => s as SourceId;
export type UnitKey = Brand<string, 'UnitKey'>;
export type EntityTypeKey = Brand<string, 'EntityTypeKey'>;
export type PackId = Brand<string, 'PackId'>;
export type Fingerprint = Brand<string, 'Fingerprint'>;
export { type AttributeKey, type CapabilityKey, type DerivationId, attributeKey, capabilityKey, derivationId } from '@camefa/engine-contracts';
