declare const BRAND: unique symbol;
export type Brand<T, B extends string> = T & { readonly [BRAND]: B };
export type EntityId = Brand<string, 'EntityId'>;
export type ClaimId = Brand<string, 'ClaimId'>;
export type SourceId = Brand<string, 'SourceId'>;
export const entityId = (s: string): EntityId => s as EntityId;
export const claimId = (s: string): ClaimId => s as ClaimId;
export const sourceId = (s: string): SourceId => s as SourceId;
export const attributeKey = (s: string): AttributeKey => s as AttributeKey;
export const capabilityKey = (s: string): CapabilityKey => s as CapabilityKey;
export const derivationId = (s: string): DerivationId => s as DerivationId;
export type UnitKey = Brand<string, 'UnitKey'>;
export type EntityTypeKey = Brand<string, 'EntityTypeKey'>;
export type PackId = Brand<string, 'PackId'>;
export type Fingerprint = Brand<string, 'Fingerprint'>;
export type AttributeKey = Brand<string, 'AttributeKey'>;
export type CapabilityKey = Brand<string, 'CapabilityKey'>;
export type DerivationId = Brand<string, 'DerivationId'>;